[package]
name = "graphics-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
image = "0.24.2"
rayon = "1.5"
pbr = "1.0.4"
clap = "3.1.18"