pub mod point;
pub mod vector;
pub mod ray;
pub mod sphere;
pub mod plane;
pub mod camera;
pub mod intersectable;
pub mod intersection;
pub mod scene;
pub mod light;
pub mod macros;
pub mod renderer;
pub mod color;
pub mod triangle;
pub mod mesh;
pub mod matrix;
pub mod aabb;
pub mod bvh;

pub const EPSILON: f32 = 1e-6;